// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C2_Final.Models
{
    public partial class Account
    {
        public string AccountNumber { get; set; }
        public string MemberId { get; set; }
        public string InstitutionId { get; set; }
        public string Value { get; set; }
    }
}