// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C2_Final.Models
{
    public partial class Institution
    {
        public string InstitutionId { get; set; }
        public string Name { get; set; }
        public string RoutingNumber { get; set; }
        public string Address { get; set; }
    }
}